### ISSUE TITLE
Addresses without balance

### ISSUE THREAD

**Issue by gamgnam321** [ameijer/bitcoin_wallet_recovery_tool#15]
Hi, my friend!

Is it possible to deduce addresses with passwords without checking the balance?

Thanks for your work!

**Comment by ameijer** [comment]
Hi! 

Unfortunately, I don't think it is possible. The issue is that wallets with passwords are encrypted, so the bytes this tool uses to generate addresses to check will be completely scrambled and random - they will all be random 0 balance addresses, even if  you know there are addresses with bitcoin inside the encrypted wallet. 

Hope this helps to clarify!
