### ISSUE TITLE
BitcoinCash

### ISSUE THREAD

**Issue by elstevega** [ameijer/bitcoin_wallet_recovery_tool#2]
How would one go about modifying this code to check for BitcoinCash keys? I lost some BCH in a hard drive crash and would be willing to throw a few bucks your way for an update... :)

**Comment by ameijer** [comment]
Hi There! 

Thanks for your interest. Unfortunately, I am not in a position to add altcoin support at this time. You could possibly modify it by checking a bcash explorer site URL (bitcoin.com?) , rather than the URL I use now, to find out how many bcash coins you have. If you are able to modify it, I would happily merge a PR!

**Comment by elstevega** [comment]
Thanks for the response - I was able to brute force scan my drive for valid
looking addresses and got lucky.

Will keep this info on hand.

Happy holidays
